[build]
builder = "nixpacks"
buildCommand = "cd core-api && pip install -r requirements.txt"

[deploy]
startCommand = "cd core-api && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 